module.exports = {
  projects: [
    '<rootDir>/libs/proto',
    '<rootDir>/apps/api',
    '<rootDir>/apps/client',
    '<rootDir>/apps/portfolio',
    '<rootDir>/apps/documentation',
    '<rootDir>/libs/backend-auth',
    '<rootDir>/libs/backend-github',
    '<rootDir>/libs/backend-grpc',
    '<rootDir>/libs/backend-mailer',
    '<rootDir>/libs/backend-interfaces',
    '<rootDir>/libs/backend-logger',
    '<rootDir>/libs/backend-websocket',
    '<rootDir>/libs/client-components',
    '<rootDir>/libs/client-core',
    '<rootDir>/libs/client-material',
    '<rootDir>/libs/client-services',
    '<rootDir>/libs/client-sidebar',
    '<rootDir>/libs/client-store',
    '<rootDir>/libs/client-translate',
    '<rootDir>/libs/client-util',
    '<rootDir>/libs/client-unit-testing',
    '<rootDir>/libs/client-portfolio',
  ],
};
